# Generated by Django 4.0.3 on 2023-10-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='context',
            new_name='content',
        ),
    ]
